[package]
name = "naf"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
nom = "7.1.3"
[dependencies.zstd]
version = "0.12.4"
features = ["experimental"]

[dev-dependencies]
memmap = "0.7.0"