name: Rust
on:
  - push
  - pull_request

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Setup Rust stable
        uses: dtolnay/rust-toolchain@stable
        with:
          components: rustfmt
      - name: Check code format
        run: cargo fmt --all -- --check
  check:
    name: Check (${{ matrix.rust-toolchain }})
    runs-on: ubuntu-latest
    needs: lint
    strategy:
      matrix:
        rust-toolchain:
          - stable
          - beta
          - nightly
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    - name: Setup Rust ${{ matrix.rust-toolchain }}
      uses: dtolnay/rust-toolchain@master
      with:
        toolchain: ${{ matrix.rust-toolchain }}
    - name: Setup cache for cargo
      uses: actions/cache@v3
      with:
        path: target
        key: ${{ runner.os }}-cargo-${{ matrix.rust-toolchain }}
    - name: Check code
      run: cargo check
      env: 
        PYO3_CROSS_PYTHON_VERSION: "3.11"
  test:
    name: Test (${{ matrix.rust-toolchain }})
    runs-on: ubuntu-latest
    needs: check
    strategy:
      matrix:
        rust-toolchain:
          - stable
          - beta
          - nightly
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    - name: Setup Rust ${{ matrix.rust-toolchain }}
      uses: dtolnay/rust-toolchain@master
      with:
        toolchain: ${{ matrix.rust-toolchain }}
    - name: Setup cache for cargo
      uses: actions/cache@v3
      with:
        path: target
        key: ${{ runner.os }}-cargo-${{ matrix.rust-toolchain }}
    - name: Test code
      run: cargo test
  cover:
    name: Coverage
    runs-on: ubuntu-latest
    needs: test
    if: "!startsWith(github.ref, 'refs/tags/v')"
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    - name: Setup Rust stable
      uses: dtolnay/rust-toolchain@stable
    - name: Setup cache for cargo
      uses: actions/cache@v3
      with:
        path: target
        key: ${{ runner.os }}-cargo-${{ matrix.rust-toolchain }}
    - name: Install cargo-tarpaulin
      run: cargo install cargo-tarpaulin
    - name: Measure code coverage
      run: cargo tarpaulin -v --out Xml --ciserver github-actions
    - name: Upload to Codecov
      uses: codecov/codecov-action@v3
      with:
        env_vars: OS
        fail_ci_if_error: false
        token: ${{ secrets.CODECOV_TOKEN }}
        codecov_curl_args: "--globoff"
        verbose: true
  publish:
    needs: test
    runs-on: ubuntu-latest
    if: "startsWith(github.ref, 'refs/tags/v')"
    environment: Crates.io
    name: Publish crates
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    - name: Setup Rust ${{ matrix.rust-toolchain }}
      uses: dtolnay/rust-toolchain@stable
    - name: Package and publish nafcodec
      run: cargo publish -p nafcodec --token ${{ secrets.CRATES_IO_TOKEN }}
    - name: Package and publish nafcodec-py
      run: cargo publish -p nafcodec-py --token ${{ secrets.CRATES_IO_TOKEN }}
  release:
    environment: GitHub Releases
    runs-on: ubuntu-latest
    if: "startsWith(github.ref, 'refs/tags/v')"
    name: Release
    needs: publish
    permissions:
      contents: write
      pull-requests: read
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    - name: Release a Changelog
      uses: rasmus-saks/release-a-changelog-action@v1.0.1
      with:
        github-token: '${{ secrets.GITHUB_TOKEN }}'
